name: Sync upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT_SYNC }}   # tvůj PAT
      BRANCH: master                      # změň na main, pokud je potřeba
    steps:
      - name: Sync fork with upstream
        run: |
          set -e
          gh api \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/merge-upstream" \
            -f branch="$BRANCH"
